name: Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run from prebuilt Docker image
    steps:
      - uses: actions/checkout@v1

      - name: Launch Hazelcast Cluster
        run: docker-compose -f hazelcast-cluster.yml up -d

      - name: Launch Quarkus Applications
        run: docker-compose -f hazelcast-quarkus-client.yml up -d

      - name: Verify
        run: |
          echo "Setting key=key_1&value=value_1"
          curl -s -X GET "localhost:8081/hazelcast/put?key=key_1&value=value_1" && sleep 1

          echo
          echo "Retrieving value for key=key_1"
          readonly result="$(curl "localhost:8080/hazelcast/get?key=key_1" | jq -r .value)"
          echo "Retrieved key_1 value: [$result]"
          [[ "$result" = "value_1" ]] || exit 1